// Real event data pulled from the live KLP microsites on 2026-08-22.
// See /context/data-sources.md in the repo root for provenance.
// Ticket prices are never invented here — every event links out to its
// real ticketing page instead.

export const events = [
  {
    slug: "white-rose-gala",
    name: "White Rose Gala",
    theme: "New Year's Eve — Gatsby-Style Elegance",
    tagline: "Deco, diamonds & decibels.",
    venue: "The Ritz-Carlton Denver",
    address: "1881 Curtis Street, Denver, CO",
    date: "2026-12-31",
    dateLabel: "Thursday, December 31, 2026",
    time: "8:00 PM – 1:00 AM",
    ageRestriction: "21+",
    highlights: [
      "Live band + DJ fusion — swing meets modern beats",
      "Theatrical acts, showgirl performances & speakeasy dance floor",
      "Midnight balloon drop, Gatsby casino gaming",
      "Hotel takeover — ride the elevator home",
    ],
    ticketUrl: "https://newyearspartydenver.com/",
  },
  {
    slug: "denver-mardi-gras",
    name: "Denver Mardi Gras",
    theme: "NOLA Hotel Takeover",
    tagline: "NOLA stops. Denver doesn’t!",
    venue: "DoubleTree by Hilton — DTC",
    address: "7801 E Orchard Rd, Greenwood Village, CO",
    date: "2027-02-27",
    dateLabel: "Saturday, February 27, 2027",
    time: "Doors 7:00 PM",
    ageRestriction: "21+",
    highlights: [
      "Live music all night — brass, beats & basslines",
      "Roaming performers and stilt walkers on every floor",
      "VIP: drinks included all night, dedicated bars, priority access",
      "Discounted hotel rooms — atrium rooms sell out every year",
    ],
    ticketUrl: "https://denvermardigras.com/",
  },
  {
    slug: "denver-derby-day",
    name: "Denver Derby Day",
    theme: "The Kentucky Derby, Elevated Mile-High Style",
    tagline: "Dress to impress — and dress to win.",
    venue: "The Ritz-Carlton Denver",
    address: "1881 Curtis Street, Denver, CO",
    date: "2027-05-01",
    dateLabel: "Saturday, May 1, 2027",
    time: "Doors 1:00 PM",
    ageRestriction: "21+",
    highlights: [
      "Multiple 10-foot screens for the race, two dance floors",
      "Best Dressed & Derby Fashion Contest — runway competition",
      "Mint Juleps and signature cocktails all day",
      "After Party (5–8 PM) included with admission",
    ],
    ticketUrl: "https://denverderby.org/",
  },
  {
    slug: "paranormal-palace",
    name: "Paranormal Palace",
    theme: "Denver Halloween Takeover",
    tagline: "$2,500 Costume Contest. Mandatory costumes.",
    venue: "DoubleTree by Hilton — DTC",
    address: "7801 E Orchard Rd, Greenwood Village, CO",
    date: "2026-10-31",
    dateLabel: "Saturday, October 31, 2026",
    time: "8:00 PM – 1:00 AM",
    ageRestriction: "21+ · costumes required",
    highlights: [
      "8,000 sq ft haunted forest with stage shows",
      "Multi-level atrium — 41 balcony rooms overlooking the floor",
      "20+ performers, multiple DJs, interactive exhibits",
      "VIP: four exclusive zones, private bars, table reservations",
    ],
    ticketUrl: "https://denverhalloween.org/",
  },
  {
    slug: "jammy-jam",
    name: "Jammy Jam",
    theme: "Denver's Grown-Up Pajama Party",
    tagline: "Bedtime, turned into a celebration.",
    venue: "The Church, Denver",
    address: "Denver, CO",
    date: "2026-09-19",
    dateLabel: "Saturday, September 19, 2026",
    time: "7:00 PM – 11:00 PM · After Party 11 PM–2 AM",
    ageRestriction: "21+",
    highlights: [
      "Live performances, DJ & dance floor, immersive installations",
      "VIP: four private areas including a rooftop deck",
      "After Party with its own bar, dance floor & VIP Grotto",
      "Matching pajamas encouraged — come cozy, come glamorous",
    ],
    ticketUrl: "https://jammyjam.net/",
  },
];
